export const phrases = [
  // two word
  "move south",
  "move north",
  "move west",
  "move east",
  "get address",
  "phone number",
  "first name",
  "last name",
  "rewrite file",
  "count words",
  "set timer",
  "download images",
  "translate word",

  // three word
  "date of birth",
  "number of items",
  "get first name",
  "get last name",
  "write to file",
  "reload table data",
  "add new item",
  "create new person",
  "delete last item",
  "upload all files",
  "find last element",
  "update profile picture",
  "restore deleted documents",
];
